@startuml ClassDiagram_01_Core
' v0.1.11
' ステレオタイプの色設定
skinparam class {
    BackgroundColor<<MonoBehaviour>> LightBlue
    BackgroundColor<<ScriptableObject>> LightGreen
    BackgroundColor<<Interface>> LightYellow
}

' --- Interfaces ---
interface IMovable <<Interface>>
interface IShootable <<Interface>>

' --- Managers ---
class SystemManager <<MonoBehaviour>>
class DanmakuGameManager <<MonoBehaviour>>

' --- Core Abstract Classes ---
abstract class GameEntityController <<MonoBehaviour>>
class GameEntity <<ScriptableObject>>
class GameEntityProperty <<ScriptableObject>>
abstract class PatternBase <<ScriptableObject>>
abstract class EmissionShape <<ScriptableObject>>
abstract class GameParameter <<ScriptableObject>>

' --- 継承関係 ---
IMovable <|.. GameEntityController
IShootable <|.. GameEntityController
PatternBase <|-- EmissionShape

' --- 関連 ---
GameEntityController o-- GameEntity : "_entity"
GameEntity o-- "1" GameEntityProperty : "property"
GameEntityProperty o-- PatternBase : "ShootPattern / MovePattern"

@enduml
